### ISSUE TITLE
Add live example pages

### ISSUE THREAD

**Issue by aborruso** [MaxDragonheart/DirectOpenLayers#1]
Hi,
I have seen you have created and listed examples pages.

I think it would be useful to add also the URLs of the live version of the example pages.

You could use simply this repo and github pages. You would have a live website without changing anything in the repo.

**Comment by MaxDragonheart** [comment]
Hi,
thank you for the suggestion. :+1: 
Is it possible to add some live example [here](https://maxdragonheart.github.io/DirectOpenLayers/) then?
Yesterday I've created the page but, honestly, I've not read deepen if it is possible. I'll do this as soon as possible.
Alternatively I can create a new section on my personal website with which I publish live examples.

**Comment by aborruso** [comment]
> Yesterday I've created the page but, honestly, I've not read deepen if it is possible. I'll do this as soon as possible.

Yes it's possible: every html page you insert here, will be available at https://maxdragonheart.github.io/DirectOpenLayers/

In example the source of [this webpage](https://ondata.github.io/30cappa/mappa.html?id=010008) is [this file](https://github.com/ondata/30cappa/blob/main/mappa.html).

**Comment by MaxDragonheart** [comment]
I'm using [Webpack](https://webpack.js.org/) for manage DirectOpenLayers and it's not possible to use import statement outside a module.
Probably the solution is to use my personal website for the example pages but now it is not ready to use Webpack.
I hope that I'll do this as soon as possible, until then this issue will remain open.

**Comment by MaxDragonheart** [comment]
I've fund a solution [here](https://maxdragonheart.github.io/DirectOpenLayers/docs/1-quick-start/index.html).
I'm updating the [main page](https://maxdragonheart.github.io/DirectOpenLayers/) with the example maps.
Thank you for the suggestion :100:
